name: CI
on:
  pull_request:
  push:
jobs:
  secrets:
    name: Check for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@main
  xslt-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Saxon
        run: sudo apt-get update && sudo apt-get install -y libsaxonb-java
      - name: Run XSLT tests
        run: cd src/main/ml-modules/root/judgments/xslts/ && bash tests/run-tests.sh ; cd -